apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
