apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
    - nodePort: 31123
      port: 8123
      protocol: TCP
  type: NodePort
  externalIPs:
    - 192.168.1.240
