apiVersion: networking.k8s.io/v1 # CHANGED: migrated from deprecated v1beta1 API
kind: Ingress
metadata:
  namespace: default
  name: home-assistant-ingress
spec:
  rules:
      # TODO: get this working using pihole DNS
    - host: home.assistant
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
