apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: pihole-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  defaultBackend:
    service:
      name: pihole
      port:
        number: 80
  rules:
    - host: pi.hole
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: pihole
                port:
                  number: 80
